apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: mozmeao-poc
  INFLUXDB_URL: https://greatscott-67880fdb.influxcloud.net:8086
  INFLUXDB_USER: babycarl
  INFLUXDB_USER_PASSWORD: 

